apply plugin: 'com.android.library'

android {
    namespace "com.mavidev.smsretriever"
    compileSdkVersion project.hasProperty('compileSdkVersion') ? project.compileSdkVersion : 34
    
    defaultConfig {
        minSdkVersion project.hasProperty('minSdkVersion') ? project.minSdkVersion : 22
        targetSdkVersion project.hasProperty('targetSdkVersion') ? project.targetSdkVersion : 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    // Vinculación nativa a la librería core de Capacitor en Android
    implementation project(':capacitor-android')
    
    // Servicios de Google Play para SMS Retriever API
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:18.1.0'

    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test.ext:junit:1.1.5"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.5.1"
}